//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policial.ServicePolicial {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UsuActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuClaveAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuPassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsuActivo {
            get {
                return this.UsuActivoField;
            }
            set {
                if ((this.UsuActivoField.Equals(value) != true)) {
                    this.UsuActivoField = value;
                    this.RaisePropertyChanged("UsuActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuClaveAcceso {
            get {
                return this.UsuClaveAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuClaveAccesoField, value) != true)) {
                    this.UsuClaveAccesoField = value;
                    this.RaisePropertyChanged("UsuClaveAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuId {
            get {
                return this.UsuIdField;
            }
            set {
                if ((this.UsuIdField.Equals(value) != true)) {
                    this.UsuIdField = value;
                    this.RaisePropertyChanged("UsuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuNombre {
            get {
                return this.UsuNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuNombreField, value) != true)) {
                    this.UsuNombreField = value;
                    this.RaisePropertyChanged("UsuNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuPass {
            get {
                return this.UsuPassField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuPassField, value) != true)) {
                    this.UsuPassField = value;
                    this.RaisePropertyChanged("UsuPass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCuota", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class TipoCuota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecModifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TCActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TCIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TCMontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdModifField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecAlta {
            get {
                return this.FecAltaField;
            }
            set {
                if ((this.FecAltaField.Equals(value) != true)) {
                    this.FecAltaField = value;
                    this.RaisePropertyChanged("FecAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecModif {
            get {
                return this.FecModifField;
            }
            set {
                if ((this.FecModifField.Equals(value) != true)) {
                    this.FecModifField = value;
                    this.RaisePropertyChanged("FecModif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TCActivo {
            get {
                return this.TCActivoField;
            }
            set {
                if ((this.TCActivoField.Equals(value) != true)) {
                    this.TCActivoField = value;
                    this.RaisePropertyChanged("TCActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCDescripcion {
            get {
                return this.TCDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TCDescripcionField, value) != true)) {
                    this.TCDescripcionField = value;
                    this.RaisePropertyChanged("TCDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TCId {
            get {
                return this.TCIdField;
            }
            set {
                if ((this.TCIdField.Equals(value) != true)) {
                    this.TCIdField = value;
                    this.RaisePropertyChanged("TCId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TCMonto {
            get {
                return this.TCMontoField;
            }
            set {
                if ((this.TCMontoField.Equals(value) != true)) {
                    this.TCMontoField = value;
                    this.RaisePropertyChanged("TCMonto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuIdAlta {
            get {
                return this.UsuIdAltaField;
            }
            set {
                if ((this.UsuIdAltaField.Equals(value) != true)) {
                    this.UsuIdAltaField = value;
                    this.RaisePropertyChanged("UsuIdAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuIdModif {
            get {
                return this.UsuIdModifField;
            }
            set {
                if ((this.UsuIdModifField.Equals(value) != true)) {
                    this.UsuIdModifField = value;
                    this.RaisePropertyChanged("UsuIdModif");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Socio", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Socio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecModifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SocAtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SocCIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SocFechaEgresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SocFechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SocFechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SocIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocMotivoEgresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocPrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocPrimerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocSegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocSegundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SocTipoCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdModifField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecAlta {
            get {
                return this.FecAltaField;
            }
            set {
                if ((this.FecAltaField.Equals(value) != true)) {
                    this.FecAltaField = value;
                    this.RaisePropertyChanged("FecAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecModif {
            get {
                return this.FecModifField;
            }
            set {
                if ((this.FecModifField.Equals(value) != true)) {
                    this.FecModifField = value;
                    this.RaisePropertyChanged("FecModif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SocAtivo {
            get {
                return this.SocAtivoField;
            }
            set {
                if ((this.SocAtivoField.Equals(value) != true)) {
                    this.SocAtivoField = value;
                    this.RaisePropertyChanged("SocAtivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SocCI {
            get {
                return this.SocCIField;
            }
            set {
                if ((this.SocCIField.Equals(value) != true)) {
                    this.SocCIField = value;
                    this.RaisePropertyChanged("SocCI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocCelular {
            get {
                return this.SocCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.SocCelularField, value) != true)) {
                    this.SocCelularField = value;
                    this.RaisePropertyChanged("SocCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocDireccion {
            get {
                return this.SocDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.SocDireccionField, value) != true)) {
                    this.SocDireccionField = value;
                    this.RaisePropertyChanged("SocDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocEmail {
            get {
                return this.SocEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SocEmailField, value) != true)) {
                    this.SocEmailField = value;
                    this.RaisePropertyChanged("SocEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SocFechaEgreso {
            get {
                return this.SocFechaEgresoField;
            }
            set {
                if ((this.SocFechaEgresoField.Equals(value) != true)) {
                    this.SocFechaEgresoField = value;
                    this.RaisePropertyChanged("SocFechaEgreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SocFechaIngreso {
            get {
                return this.SocFechaIngresoField;
            }
            set {
                if ((this.SocFechaIngresoField.Equals(value) != true)) {
                    this.SocFechaIngresoField = value;
                    this.RaisePropertyChanged("SocFechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SocFechaNacimiento {
            get {
                return this.SocFechaNacimientoField;
            }
            set {
                if ((this.SocFechaNacimientoField.Equals(value) != true)) {
                    this.SocFechaNacimientoField = value;
                    this.RaisePropertyChanged("SocFechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SocId {
            get {
                return this.SocIdField;
            }
            set {
                if ((this.SocIdField.Equals(value) != true)) {
                    this.SocIdField = value;
                    this.RaisePropertyChanged("SocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocMotivoEgreso {
            get {
                return this.SocMotivoEgresoField;
            }
            set {
                if ((object.ReferenceEquals(this.SocMotivoEgresoField, value) != true)) {
                    this.SocMotivoEgresoField = value;
                    this.RaisePropertyChanged("SocMotivoEgreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocObservaciones {
            get {
                return this.SocObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.SocObservacionesField, value) != true)) {
                    this.SocObservacionesField = value;
                    this.RaisePropertyChanged("SocObservaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocPrimerApellido {
            get {
                return this.SocPrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SocPrimerApellidoField, value) != true)) {
                    this.SocPrimerApellidoField = value;
                    this.RaisePropertyChanged("SocPrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocPrimerNombre {
            get {
                return this.SocPrimerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SocPrimerNombreField, value) != true)) {
                    this.SocPrimerNombreField = value;
                    this.RaisePropertyChanged("SocPrimerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocSegundoApellido {
            get {
                return this.SocSegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SocSegundoApellidoField, value) != true)) {
                    this.SocSegundoApellidoField = value;
                    this.RaisePropertyChanged("SocSegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocSegundoNombre {
            get {
                return this.SocSegundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SocSegundoNombreField, value) != true)) {
                    this.SocSegundoNombreField = value;
                    this.RaisePropertyChanged("SocSegundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocTel {
            get {
                return this.SocTelField;
            }
            set {
                if ((object.ReferenceEquals(this.SocTelField, value) != true)) {
                    this.SocTelField = value;
                    this.RaisePropertyChanged("SocTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SocTipoCuota {
            get {
                return this.SocTipoCuotaField;
            }
            set {
                if ((this.SocTipoCuotaField.Equals(value) != true)) {
                    this.SocTipoCuotaField = value;
                    this.RaisePropertyChanged("SocTipoCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuIdAlta {
            get {
                return this.UsuIdAltaField;
            }
            set {
                if ((this.UsuIdAltaField.Equals(value) != true)) {
                    this.UsuIdAltaField = value;
                    this.RaisePropertyChanged("UsuIdAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuIdModif {
            get {
                return this.UsuIdModifField;
            }
            set {
                if ((this.UsuIdModifField.Equals(value) != true)) {
                    this.UsuIdModifField = value;
                    this.RaisePropertyChanged("UsuIdModif");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuota", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Cuota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuotaAAAAMMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CuotaFechaDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CuotaFechaHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CuotaFechaPagaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CuotaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CuotaPagaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CuotaTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecModifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SocIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Policial.ServicePolicial.TipoCuota TCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdModifField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuotaAAAAMM {
            get {
                return this.CuotaAAAAMMField;
            }
            set {
                if ((object.ReferenceEquals(this.CuotaAAAAMMField, value) != true)) {
                    this.CuotaAAAAMMField = value;
                    this.RaisePropertyChanged("CuotaAAAAMM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CuotaFechaDesde {
            get {
                return this.CuotaFechaDesdeField;
            }
            set {
                if ((this.CuotaFechaDesdeField.Equals(value) != true)) {
                    this.CuotaFechaDesdeField = value;
                    this.RaisePropertyChanged("CuotaFechaDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CuotaFechaHasta {
            get {
                return this.CuotaFechaHastaField;
            }
            set {
                if ((this.CuotaFechaHastaField.Equals(value) != true)) {
                    this.CuotaFechaHastaField = value;
                    this.RaisePropertyChanged("CuotaFechaHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CuotaFechaPaga {
            get {
                return this.CuotaFechaPagaField;
            }
            set {
                if ((this.CuotaFechaPagaField.Equals(value) != true)) {
                    this.CuotaFechaPagaField = value;
                    this.RaisePropertyChanged("CuotaFechaPaga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CuotaId {
            get {
                return this.CuotaIdField;
            }
            set {
                if ((this.CuotaIdField.Equals(value) != true)) {
                    this.CuotaIdField = value;
                    this.RaisePropertyChanged("CuotaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CuotaPaga {
            get {
                return this.CuotaPagaField;
            }
            set {
                if ((this.CuotaPagaField.Equals(value) != true)) {
                    this.CuotaPagaField = value;
                    this.RaisePropertyChanged("CuotaPaga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CuotaTipo {
            get {
                return this.CuotaTipoField;
            }
            set {
                if ((this.CuotaTipoField.Equals(value) != true)) {
                    this.CuotaTipoField = value;
                    this.RaisePropertyChanged("CuotaTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecAlta {
            get {
                return this.FecAltaField;
            }
            set {
                if ((this.FecAltaField.Equals(value) != true)) {
                    this.FecAltaField = value;
                    this.RaisePropertyChanged("FecAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecModif {
            get {
                return this.FecModifField;
            }
            set {
                if ((this.FecModifField.Equals(value) != true)) {
                    this.FecModifField = value;
                    this.RaisePropertyChanged("FecModif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SocId {
            get {
                return this.SocIdField;
            }
            set {
                if ((this.SocIdField.Equals(value) != true)) {
                    this.SocIdField = value;
                    this.RaisePropertyChanged("SocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Policial.ServicePolicial.TipoCuota TC {
            get {
                return this.TCField;
            }
            set {
                if ((object.ReferenceEquals(this.TCField, value) != true)) {
                    this.TCField = value;
                    this.RaisePropertyChanged("TC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuIdAlta {
            get {
                return this.UsuIdAltaField;
            }
            set {
                if ((this.UsuIdAltaField.Equals(value) != true)) {
                    this.UsuIdAltaField = value;
                    this.RaisePropertyChanged("UsuIdAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuIdModif {
            get {
                return this.UsuIdModifField;
            }
            set {
                if ((this.UsuIdModifField.Equals(value) != true)) {
                    this.UsuIdModifField = value;
                    this.RaisePropertyChanged("UsuIdModif");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NucleoFamiliar", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class NucleoFamiliar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecModifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NFActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NFCIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NFCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NFFechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NFIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NFPrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NFPrimerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NFSegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NFSegundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NFTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NFobservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NfTipoVinculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SocIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdModifField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecAlta {
            get {
                return this.FecAltaField;
            }
            set {
                if ((this.FecAltaField.Equals(value) != true)) {
                    this.FecAltaField = value;
                    this.RaisePropertyChanged("FecAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecModif {
            get {
                return this.FecModifField;
            }
            set {
                if ((this.FecModifField.Equals(value) != true)) {
                    this.FecModifField = value;
                    this.RaisePropertyChanged("FecModif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NFActivo {
            get {
                return this.NFActivoField;
            }
            set {
                if ((this.NFActivoField.Equals(value) != true)) {
                    this.NFActivoField = value;
                    this.RaisePropertyChanged("NFActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NFCI {
            get {
                return this.NFCIField;
            }
            set {
                if ((this.NFCIField.Equals(value) != true)) {
                    this.NFCIField = value;
                    this.RaisePropertyChanged("NFCI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NFCelular {
            get {
                return this.NFCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.NFCelularField, value) != true)) {
                    this.NFCelularField = value;
                    this.RaisePropertyChanged("NFCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NFFechaNacimiento {
            get {
                return this.NFFechaNacimientoField;
            }
            set {
                if ((this.NFFechaNacimientoField.Equals(value) != true)) {
                    this.NFFechaNacimientoField = value;
                    this.RaisePropertyChanged("NFFechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NFId {
            get {
                return this.NFIdField;
            }
            set {
                if ((this.NFIdField.Equals(value) != true)) {
                    this.NFIdField = value;
                    this.RaisePropertyChanged("NFId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NFPrimerApellido {
            get {
                return this.NFPrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.NFPrimerApellidoField, value) != true)) {
                    this.NFPrimerApellidoField = value;
                    this.RaisePropertyChanged("NFPrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NFPrimerNombre {
            get {
                return this.NFPrimerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NFPrimerNombreField, value) != true)) {
                    this.NFPrimerNombreField = value;
                    this.RaisePropertyChanged("NFPrimerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NFSegundoApellido {
            get {
                return this.NFSegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.NFSegundoApellidoField, value) != true)) {
                    this.NFSegundoApellidoField = value;
                    this.RaisePropertyChanged("NFSegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NFSegundoNombre {
            get {
                return this.NFSegundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NFSegundoNombreField, value) != true)) {
                    this.NFSegundoNombreField = value;
                    this.RaisePropertyChanged("NFSegundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NFTel {
            get {
                return this.NFTelField;
            }
            set {
                if ((object.ReferenceEquals(this.NFTelField, value) != true)) {
                    this.NFTelField = value;
                    this.RaisePropertyChanged("NFTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NFobservaciones {
            get {
                return this.NFobservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.NFobservacionesField, value) != true)) {
                    this.NFobservacionesField = value;
                    this.RaisePropertyChanged("NFobservaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NfTipoVinculo {
            get {
                return this.NfTipoVinculoField;
            }
            set {
                if ((object.ReferenceEquals(this.NfTipoVinculoField, value) != true)) {
                    this.NfTipoVinculoField = value;
                    this.RaisePropertyChanged("NfTipoVinculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SocId {
            get {
                return this.SocIdField;
            }
            set {
                if ((this.SocIdField.Equals(value) != true)) {
                    this.SocIdField = value;
                    this.RaisePropertyChanged("SocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuIdAlta {
            get {
                return this.UsuIdAltaField;
            }
            set {
                if ((this.UsuIdAltaField.Equals(value) != true)) {
                    this.UsuIdAltaField = value;
                    this.RaisePropertyChanged("UsuIdAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuIdModif {
            get {
                return this.UsuIdModifField;
            }
            set {
                if ((this.UsuIdModifField.Equals(value) != true)) {
                    this.UsuIdModifField = value;
                    this.RaisePropertyChanged("UsuIdModif");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Impresion", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Impresion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Policial.ServicePolicial.Cuota CuotaImpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Policial.ServicePolicial.Socio SocioImpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Policial.ServicePolicial.Cuota CuotaImp {
            get {
                return this.CuotaImpField;
            }
            set {
                if ((object.ReferenceEquals(this.CuotaImpField, value) != true)) {
                    this.CuotaImpField = value;
                    this.RaisePropertyChanged("CuotaImp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Policial.ServicePolicial.Socio SocioImp {
            get {
                return this.SocioImpField;
            }
            set {
                if ((object.ReferenceEquals(this.SocioImpField, value) != true)) {
                    this.SocioImpField = value;
                    this.RaisePropertyChanged("SocioImp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePolicial.IServicePolicial")]
    public interface IServicePolicial {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/Login", ReplyAction="http://tempuri.org/IServicePolicial/LoginResponse")]
        Policial.ServicePolicial.Usuario Login(string _Usuario, string _Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/ListarTC", ReplyAction="http://tempuri.org/IServicePolicial/ListarTCResponse")]
        Policial.ServicePolicial.TipoCuota[] ListarTC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/AltaSocio", ReplyAction="http://tempuri.org/IServicePolicial/AltaSocioResponse")]
        bool AltaSocio(Policial.ServicePolicial.Socio s, Policial.ServicePolicial.Cuota c, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/ActivarSocio", ReplyAction="http://tempuri.org/IServicePolicial/ActivarSocioResponse")]
        bool ActivarSocio(Policial.ServicePolicial.Socio s, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/BuscarSocioPorCI", ReplyAction="http://tempuri.org/IServicePolicial/BuscarSocioPorCIResponse")]
        Policial.ServicePolicial.Socio BuscarSocioPorCI(int _cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/ListarSocios", ReplyAction="http://tempuri.org/IServicePolicial/ListarSociosResponse")]
        Policial.ServicePolicial.Socio[] ListarSocios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/ModificarSocio", ReplyAction="http://tempuri.org/IServicePolicial/ModificarSocioResponse")]
        bool ModificarSocio(Policial.ServicePolicial.Socio s, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/BajaSocio", ReplyAction="http://tempuri.org/IServicePolicial/BajaSocioResponse")]
        bool BajaSocio(Policial.ServicePolicial.Socio c, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/AltaNucleoFamiliar", ReplyAction="http://tempuri.org/IServicePolicial/AltaNucleoFamiliarResponse")]
        bool AltaNucleoFamiliar(Policial.ServicePolicial.NucleoFamiliar c, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/ModificarNF", ReplyAction="http://tempuri.org/IServicePolicial/ModificarNFResponse")]
        bool ModificarNF(Policial.ServicePolicial.NucleoFamiliar c, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/BajaNF", ReplyAction="http://tempuri.org/IServicePolicial/BajaNFResponse")]
        bool BajaNF(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/BuscarNucleoFamiliarPorCI", ReplyAction="http://tempuri.org/IServicePolicial/BuscarNucleoFamiliarPorCIResponse")]
        Policial.ServicePolicial.NucleoFamiliar[] BuscarNucleoFamiliarPorCI(int socId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/BuscarCuotasSocio", ReplyAction="http://tempuri.org/IServicePolicial/BuscarCuotasSocioResponse")]
        Policial.ServicePolicial.Cuota[] BuscarCuotasSocio(int socId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/AltaCuentaSocio", ReplyAction="http://tempuri.org/IServicePolicial/AltaCuentaSocioResponse")]
        bool AltaCuentaSocio(Policial.ServicePolicial.Cuota c, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/PagarCuotaSocio", ReplyAction="http://tempuri.org/IServicePolicial/PagarCuotaSocioResponse")]
        bool PagarCuotaSocio(Policial.ServicePolicial.Cuota c, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/AltaCuota", ReplyAction="http://tempuri.org/IServicePolicial/AltaCuotaResponse")]
        bool AltaCuota(Policial.ServicePolicial.TipoCuota c, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/ModificarCuota", ReplyAction="http://tempuri.org/IServicePolicial/ModificarCuotaResponse")]
        bool ModificarCuota(Policial.ServicePolicial.TipoCuota c, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/BajarCuota", ReplyAction="http://tempuri.org/IServicePolicial/BajarCuotaResponse")]
        bool BajarCuota(int id, Policial.ServicePolicial.Usuario _usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePolicial/ListarImpresion", ReplyAction="http://tempuri.org/IServicePolicial/ListarImpresionResponse")]
        Policial.ServicePolicial.Impresion[] ListarImpresion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePolicialChannel : Policial.ServicePolicial.IServicePolicial, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePolicialClient : System.ServiceModel.ClientBase<Policial.ServicePolicial.IServicePolicial>, Policial.ServicePolicial.IServicePolicial {
        
        public ServicePolicialClient() {
        }
        
        public ServicePolicialClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePolicialClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePolicialClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePolicialClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Policial.ServicePolicial.Usuario Login(string _Usuario, string _Password) {
            return base.Channel.Login(_Usuario, _Password);
        }
        
        public Policial.ServicePolicial.TipoCuota[] ListarTC() {
            return base.Channel.ListarTC();
        }
        
        public bool AltaSocio(Policial.ServicePolicial.Socio s, Policial.ServicePolicial.Cuota c, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.AltaSocio(s, c, _usu);
        }
        
        public bool ActivarSocio(Policial.ServicePolicial.Socio s, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.ActivarSocio(s, _usu);
        }
        
        public Policial.ServicePolicial.Socio BuscarSocioPorCI(int _cedula) {
            return base.Channel.BuscarSocioPorCI(_cedula);
        }
        
        public Policial.ServicePolicial.Socio[] ListarSocios() {
            return base.Channel.ListarSocios();
        }
        
        public bool ModificarSocio(Policial.ServicePolicial.Socio s, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.ModificarSocio(s, _usu);
        }
        
        public bool BajaSocio(Policial.ServicePolicial.Socio c, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.BajaSocio(c, _usu);
        }
        
        public bool AltaNucleoFamiliar(Policial.ServicePolicial.NucleoFamiliar c, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.AltaNucleoFamiliar(c, _usu);
        }
        
        public bool ModificarNF(Policial.ServicePolicial.NucleoFamiliar c, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.ModificarNF(c, _usu);
        }
        
        public bool BajaNF(int id) {
            return base.Channel.BajaNF(id);
        }
        
        public Policial.ServicePolicial.NucleoFamiliar[] BuscarNucleoFamiliarPorCI(int socId) {
            return base.Channel.BuscarNucleoFamiliarPorCI(socId);
        }
        
        public Policial.ServicePolicial.Cuota[] BuscarCuotasSocio(int socId) {
            return base.Channel.BuscarCuotasSocio(socId);
        }
        
        public bool AltaCuentaSocio(Policial.ServicePolicial.Cuota c, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.AltaCuentaSocio(c, _usu);
        }
        
        public bool PagarCuotaSocio(Policial.ServicePolicial.Cuota c, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.PagarCuotaSocio(c, _usu);
        }
        
        public bool AltaCuota(Policial.ServicePolicial.TipoCuota c, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.AltaCuota(c, _usu);
        }
        
        public bool ModificarCuota(Policial.ServicePolicial.TipoCuota c, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.ModificarCuota(c, _usu);
        }
        
        public bool BajarCuota(int id, Policial.ServicePolicial.Usuario _usu) {
            return base.Channel.BajarCuota(id, _usu);
        }
        
        public Policial.ServicePolicial.Impresion[] ListarImpresion() {
            return base.Channel.ListarImpresion();
        }
    }
}
